coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto

parsers:
  javascript:
    enable_partials: yes

comment:
  layout: "reach,diff,flags,files"
  behavior: default

ignore:
  - "test/**/*"
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "coverage/**/*"