name: Test Token Access

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Token
        run: |
          if [ -n "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "Token is configured"
          else
            echo "Token is missing"
          fi
